/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var x = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89] //231

function fibb(limit) {
  var a = 1
  var b = 1
  var sum = 0;
  while(b<limit) {
    b = a+b;
    a = b-a;
    sum +=a;
    console.log("a: " + a + "  b: " + b)
  }
  return sum
}

function fibbEven(limit) {
  var a = 1
  var b = 1
  var sum = 0;
  while(b<limit) {
    b = a+b;
    a = b-a;
    if(a%2 === 0) sum +=a
    //console.log("a: " + a + "  b: " + b)
  }
  return sum
}

console.log(fibbEven(4000000))

//4613732